# Generated by Django 4.2.23 on 2025-06-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_svc', '0002_add_read_receipt_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
