# Generated by Django 4.2.23 on 2025-06-24 13:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import integrations.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('chat_svc', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_concurrent_threads',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_users',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('favicon_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#1976d2', max_length=7)),
                ('secondary_color', models.CharField(default='#dc004e', max_length=7)),
                ('accent_color', models.CharField(default='#f57c00', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#333333', max_length=7)),
                ('font_family', models.CharField(default='Roboto, sans-serif', max_length=100)),
                ('header_font_size', models.PositiveIntegerField(default=16)),
                ('body_font_size', models.PositiveIntegerField(default=14)),
                ('sidebar_width', models.PositiveIntegerField(default=280)),
                ('header_height', models.PositiveIntegerField(default=64)),
                ('border_radius', models.PositiveIntegerField(default=4)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('email_header_color', models.CharField(default='#1976d2', max_length=7)),
                ('email_footer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='chat_svc.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sla_hours', models.PositiveIntegerField(default=24)),
                ('high_priority_sla_hours', models.PositiveIntegerField(default=4)),
                ('medium_priority_sla_hours', models.PositiveIntegerField(default=12)),
                ('low_priority_sla_hours', models.PositiveIntegerField(default=48)),
                ('enable_auto_escalation', models.BooleanField(default=True)),
                ('escalation_warning_hours', models.PositiveIntegerField(default=2)),
                ('escalation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_retention_days', models.PositiveIntegerField(default=365)),
                ('attachment_retention_days', models.PositiveIntegerField(default=90)),
                ('log_retention_days', models.PositiveIntegerField(default=1095)),
                ('enable_file_attachments', models.BooleanField(default=True)),
                ('enable_structured_replies', models.BooleanField(default=True)),
                ('enable_read_receipts', models.BooleanField(default=True)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('enable_audit_logging', models.BooleanField(default=True)),
                ('max_attachment_size_mb', models.PositiveIntegerField(default=10)),
                ('max_message_length', models.PositiveIntegerField(default=5000)),
                ('rate_limit_messages_per_minute', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='chat_svc.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic Plan'), ('professional', 'Professional Plan'), ('enterprise', 'Enterprise Plan'), ('custom', 'Custom Plan')], default='basic', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('per_user_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_contact', models.EmailField(max_length=254)),
                ('invoice_frequency', models.CharField(default='monthly', max_length=20)),
                ('current_user_count', models.PositiveIntegerField(default=0)),
                ('current_storage_gb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monthly_message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='chat_svc.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('itsm', 'IT Service Management'), ('event_bus', 'Event Bus'), ('push_notifications', 'Push Notifications'), ('email', 'Email Service'), ('sms', 'SMS Service'), ('webhook', 'Webhook'), ('api', 'External API'), ('siem', 'SIEM Integration'), ('monitoring', 'Monitoring System')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('api_key', integrations.encryption.EncryptedTextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', integrations.encryption.EncryptedTextField(blank=True, null=True)),
                ('config_data', models.JSONField(default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('retry_attempts', models.PositiveIntegerField(default=3)),
                ('event_filters', models.JSONField(default=dict, help_text='JSON filters for when to trigger this integration')),
                ('last_successful_call', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('failed_calls', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='chat_svc.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'integration_type', 'name')},
            },
        ),
    ]
