# Generated by Django 3.2 on 2025-06-11 13:11

import chat_svc.chat.encrypted_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_attachment_hashchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=chat_svc.chat.encrypted_storage.EncryptedFileSystemStorage(), upload_to='attachments/'),
        ),
    ]
