# Generated by Django 3.2 on 2025-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_db_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='invite_code',
            field=models.CharField(default='DEFAULT-INVITE', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
