# Generated by Django 3.2 on 2025-06-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20250616_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontemplate',
            name='tenant',
        ),
    ]
