# Generated by Django 3.2 on 2025-06-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_questiontemplate_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together={('tenant', 'incident_id')},
        ),
    ]
