# Generated by Django 3.2 on 2025-06-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatthread_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.tenant'),
        ),
    ]
