# Generated by Django 3.2 on 2025-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_questiontemplate_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
